import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync, existsSync, mkdirSync } from "fs";
import { join, dirname } from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const ctx = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await ctx.rebuild();

	// Copy sql-wasm.wasm to plugin root
	const wasmSrc = join("node_modules", "sql.js", "dist", "sql-wasm.wasm");
	if (existsSync(wasmSrc)) {
		copyFileSync(wasmSrc, "sql-wasm.wasm");
		console.log("Copied sql-wasm.wasm to plugin root");
	} else {
		console.warn("Warning: sql-wasm.wasm not found at", wasmSrc);
	}

	process.exit(0);
} else {
	await ctx.watch();
}
